/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import dao.MunicipioDAO;
import dominio.Municipio;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author joaod
 */
public class AdicionarGastos extends javax.swing.JDialog {

    Municipio municipio;
    MunicipioDAO municipioDAO;

    /**
     * Creates new form AdicionarGastos
     */
    public AdicionarGastos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNomeMunicipio = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtSiglaEstado = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtGastoAtual = new javax.swing.JFormattedTextField();
        jbPesquisar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaMunicipios = new javax.swing.JTable();
        jBAdicionarGasto = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtGastoAdicional = new javax.swing.JFormattedTextField();
        jbNovo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Lançar gastos");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jLabel1.setText("ADICIONAR GASTOS MUNICIPAIS");

        txtNomeMunicipio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeMunicipioActionPerformed(evt);
            }
        });

        jLabel3.setText("Nome");

        jLabel7.setText("Sigla do Estado");

        txtSiglaEstado.setText("XX");
        txtSiglaEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSiglaEstadoActionPerformed(evt);
            }
        });

        jLabel4.setText("Gasto Atual");

        jbPesquisar.setText("PESQUISAR");
        jbPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPesquisarActionPerformed(evt);
            }
        });

        tabelaMunicipios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nome", "Sigla do Estado", "Populacao", "Clima", "Gastos"
            }
        ));
        tabelaMunicipios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaMunicipiosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaMunicipios);

        jBAdicionarGasto.setText("ADICIONAR GASTO");
        jBAdicionarGasto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAdicionarGastoActionPerformed(evt);
            }
        });

        jButton3.setText("SAIR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel5.setText("Gasto Adicional");

        jbNovo.setText("NOVO");
        jbNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNovoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(260, 260, 260)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(txtSiglaEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtNomeMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtGastoAtual, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtGastoAdicional))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(274, 274, 274)
                        .addComponent(jbPesquisar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 566, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(jbNovo)
                        .addGap(44, 44, 44)
                        .addComponent(jBAdicionarGasto)
                        .addGap(44, 44, 44)
                        .addComponent(jButton3)))
                .addContainerGap(154, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtNomeMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtSiglaEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtGastoAtual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtGastoAdicional, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(31, 31, 31)
                .addComponent(jbPesquisar)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBAdicionarGasto)
                    .addComponent(jButton3)
                    .addComponent(jbNovo))
                .addContainerGap(179, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeMunicipioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeMunicipioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeMunicipioActionPerformed

    private void txtSiglaEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSiglaEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSiglaEstadoActionPerformed

    private void tabelaMunicipiosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMunicipiosMouseClicked
        txtNomeMunicipio.setText(tabelaMunicipios.getValueAt(tabelaMunicipios.getSelectedRow(), 0).toString());
        txtSiglaEstado.setText(tabelaMunicipios.getValueAt(tabelaMunicipios.getSelectedRow(), 1).toString());
        txtGastoAtual.setText(tabelaMunicipios.getValueAt(tabelaMunicipios.getSelectedRow(), 4).toString());
        txtNomeMunicipio.setEnabled(false);
        txtSiglaEstado.setEnabled(false);
        txtGastoAdicional.setEnabled(true);


    }//GEN-LAST:event_tabelaMunicipiosMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        txtGastoAtual.setEnabled(false);
        txtGastoAdicional.setEnabled(false);
    }//GEN-LAST:event_formWindowActivated

    private void jbPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPesquisarActionPerformed
        try {
            String nome = txtNomeMunicipio.getText();
            String sigla = txtSiglaEstado.getText();
            listarMunicipio(nome, sigla);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Não existe o municipio municipio!");
            System.err.println(e);
        }


    }//GEN-LAST:event_jbPesquisarActionPerformed

    private void jBAdicionarGastoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAdicionarGastoActionPerformed
        try {
            String sigla = txtSiglaEstado.getText();
            String nome = txtNomeMunicipio.getText();
            float gastoAdicional = Float.parseFloat(txtGastoAdicional.getText());
            municipioDAO = new MunicipioDAO();
            municipioDAO.AdicionarGasto(sigla, nome, gastoAdicional);
            JOptionPane.showMessageDialog(null, "Valor inserido com sucesso com sucesso!");
            limpar();
            ((DefaultTableModel) tabelaMunicipios.getModel()).removeRow(0);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao insirir valor no municipio!");
            System.err.println(e);
        }


    }//GEN-LAST:event_jBAdicionarGastoActionPerformed

    private void jbNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNovoActionPerformed
        txtNomeMunicipio.setEnabled(true);
        limpar();
    }//GEN-LAST:event_jbNovoActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdicionarGastos.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdicionarGastos.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdicionarGastos.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdicionarGastos.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AdicionarGastos dialog = new AdicionarGastos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    public void listarMunicipio(String nome, String sigla) {
        try {
            municipioDAO = new MunicipioDAO();
            List<Municipio> listarMunicipios = municipioDAO.buscarMunicipio(nome, sigla);
            DefaultTableModel modelo = (DefaultTableModel) tabelaMunicipios.getModel();
            modelo.setNumRows(0);
            for (Municipio mu : listarMunicipios) {
                modelo.addRow(new Object[]{
                    mu.getNome(),
                    mu.getFk_id_estado(),
                    mu.getPopulacao(),
                    mu.getClima(),
                    mu.getGastos(),});
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Erro ao Listar os municipios");
        }
    }

    private void limpar() {
        txtNomeMunicipio.setEnabled(true);
        txtSiglaEstado.setEnabled(true);
        txtGastoAdicional.setEnabled(false);
        txtGastoAtual.setEnabled(false);
        txtNomeMunicipio.setText("");
        txtSiglaEstado.setText("");
        txtGastoAdicional.setText("");
        txtGastoAtual.setText("");
        txtNomeMunicipio.requestFocus();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAdicionarGasto;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbNovo;
    private javax.swing.JButton jbPesquisar;
    private javax.swing.JTable tabelaMunicipios;
    private javax.swing.JFormattedTextField txtGastoAdicional;
    private javax.swing.JFormattedTextField txtGastoAtual;
    private javax.swing.JFormattedTextField txtNomeMunicipio;
    private javax.swing.JTextField txtSiglaEstado;
    // End of variables declaration//GEN-END:variables

}
