/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import dao.MunicipioDAO;
import dominio.Municipio;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author joaod
 */
public class BuscaClima extends javax.swing.JDialog {

    MunicipioDAO municipioDAO;
    Municipio municipio;

    /**
     * Creates new form BuscaClima
     */
    public BuscaClima(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgClima = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        rbClimaTropical = new javax.swing.JRadioButton();
        rbClimaEquatorial = new javax.swing.JRadioButton();
        rbClimaSubtropical = new javax.swing.JRadioButton();
        rbClimaSemiarido = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaMunicipiosClima = new javax.swing.JTable();
        jbPesquisar = new javax.swing.JButton();
        jbSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Clima");
        setLocationByPlatform(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jLabel1.setText("Buscar municipios por clima ");

        jLabel2.setText("Insira o clima que deseja pesquisar: ");

        bgClima.add(rbClimaTropical);
        rbClimaTropical.setText("Tropical");

        bgClima.add(rbClimaEquatorial);
        rbClimaEquatorial.setText("Equatorial");

        bgClima.add(rbClimaSubtropical);
        rbClimaSubtropical.setText("Subtropical");

        bgClima.add(rbClimaSemiarido);
        rbClimaSemiarido.setText("Semiárido");

        tabelaMunicipiosClima.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nome", "Sigla do Estado", "Populacao", "Clima", "Gastos"
            }
        ));
        tabelaMunicipiosClima.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaMunicipiosClimaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaMunicipiosClima);

        jbPesquisar.setText("PESQUISAR");
        jbPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPesquisarActionPerformed(evt);
            }
        });

        jbSair.setText("SAIR");
        jbSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(297, 297, 297)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(rbClimaEquatorial)
                        .addGap(18, 18, 18)
                        .addComponent(rbClimaTropical)
                        .addGap(18, 18, 18)
                        .addComponent(rbClimaSubtropical)
                        .addGap(18, 18, 18)
                        .addComponent(rbClimaSemiarido))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 566, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(jbPesquisar)
                        .addGap(113, 113, 113)
                        .addComponent(jbSair)))
                .addContainerGap(170, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbClimaEquatorial)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rbClimaTropical)
                        .addComponent(rbClimaSubtropical)
                        .addComponent(rbClimaSemiarido)))
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbPesquisar)
                    .addComponent(jbSair))
                .addGap(0, 315, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tabelaMunicipiosClimaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMunicipiosClimaMouseClicked


    }//GEN-LAST:event_tabelaMunicipiosClimaMouseClicked

    private void jbPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPesquisarActionPerformed
        BuscaClima();
    }//GEN-LAST:event_jbPesquisarActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
       MunicipiosGGerais();
    }//GEN-LAST:event_formWindowActivated

    private void jbSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSairActionPerformed
        this.dispose();
    }//GEN-LAST:event_jbSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuscaClima.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuscaClima.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuscaClima.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuscaClima.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                BuscaClima dialog = new BuscaClima(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    public void MunicipiosGGerais() {
        try {
            
            municipioDAO = new MunicipioDAO();
            List<Municipio> listarMunicipios = municipioDAO.listarMunicipios();
            DefaultTableModel modelo = (DefaultTableModel) tabelaMunicipiosClima.getModel();
            modelo.setNumRows(0);
            for (Municipio mu : listarMunicipios) {
                modelo.addRow(new Object[]{
                    mu.getNome(),
                    mu.getFk_id_estado(),
                    mu.getPopulacao(),
                    mu.getClima(),
                    mu.getGastos(),});
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Erro ao Listar os municipios");
        }
    }
    
    public void BuscaClima() {
        try {
            String clima = "";
            if (rbClimaEquatorial.isSelected()) {
                clima = "Equatorial";
            } else if (rbClimaTropical.isSelected()) {
                clima = "Tropical";;
            } else if (rbClimaSubtropical.isSelected()) {
                clima = "Subtropical";
            } else if (rbClimaSemiarido.isSelected()) {
                clima = "Semiárido";
            }
            municipioDAO = new MunicipioDAO();
            List<Municipio> listarMunicipios = municipioDAO.listarMunicipiosClima(clima);
            DefaultTableModel modelo = (DefaultTableModel) tabelaMunicipiosClima.getModel();
            modelo.setNumRows(0);
            for (Municipio mu : listarMunicipios) {
                modelo.addRow(new Object[]{
                    mu.getNome(),
                    mu.getFk_id_estado(),
                    mu.getPopulacao(),
                    mu.getClima(),
                    mu.getGastos(),});
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Erro ao Listar os municipios");
        }
    }

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgClima;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbPesquisar;
    private javax.swing.JButton jbSair;
    private javax.swing.JRadioButton rbClimaEquatorial;
    private javax.swing.JRadioButton rbClimaSemiarido;
    private javax.swing.JRadioButton rbClimaSubtropical;
    private javax.swing.JRadioButton rbClimaTropical;
    private javax.swing.JTable tabelaMunicipiosClima;
    // End of variables declaration//GEN-END:variables
}
