/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import dao.MunicipioDAO;
import dominio.Municipio;
import static java.awt.Frame.MAXIMIZED_BOTH;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author chris
 */
public class MunicipioInterface extends javax.swing.JDialog {

    Municipio municipio;
    MunicipioDAO municipioDAO;

    /**
     * Creates new form Municipio
     */
    public MunicipioInterface(java.awt.Frame parent, boolean modal) {        
        super(parent, modal);        
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        bgClima = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaMunicipios = new javax.swing.JTable();
        txtNomeMunicipio = new javax.swing.JFormattedTextField();
        txtPupolacao = new javax.swing.JFormattedTextField();
        InserirJB = new javax.swing.JButton();
        NovoJB = new javax.swing.JButton();
        ExcluirJB = new javax.swing.JButton();
        txtGastos = new javax.swing.JFormattedTextField();
        SairJB = new javax.swing.JButton();
        rbClimaEquatorial = new javax.swing.JRadioButton();
        rbClimaTropical = new javax.swing.JRadioButton();
        rbClimaSubtropical = new javax.swing.JRadioButton();
        rbClimaSemiarido = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        txtSiglaEstado = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tela de Cadastro de Municipio");
        setPreferredSize(new java.awt.Dimension(793, 717));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jLabel1.setText("Nome");

        jLabel2.setText("Populacao");

        jLabel3.setText("Clima");

        jLabel4.setText("Gastos");

        tabelaMunicipios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nome", "Sigla do Estado", "Populacao", "Clima", "Gastos"
            }
        ));
        tabelaMunicipios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaMunicipiosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaMunicipios);

        txtNomeMunicipio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeMunicipioActionPerformed(evt);
            }
        });

        InserirJB.setText("INSERIR");
        InserirJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InserirJBActionPerformed(evt);
            }
        });

        NovoJB.setText("NOVO");
        NovoJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NovoJBActionPerformed(evt);
            }
        });

        ExcluirJB.setText("EXCLUIR");
        ExcluirJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExcluirJBActionPerformed(evt);
            }
        });

        SairJB.setText("SAIR");
        SairJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SairJBActionPerformed(evt);
            }
        });

        bgClima.add(rbClimaEquatorial);
        rbClimaEquatorial.setText("Equatorial");
        rbClimaEquatorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbClimaEquatorialActionPerformed(evt);
            }
        });

        bgClima.add(rbClimaTropical);
        rbClimaTropical.setText("Tropical");

        bgClima.add(rbClimaSubtropical);
        rbClimaSubtropical.setText("Subtropical");

        bgClima.add(rbClimaSemiarido);
        rbClimaSemiarido.setText("Semiárido");

        jLabel7.setText("Sigla do Estado");

        txtSiglaEstado.setText("XX");
        txtSiglaEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSiglaEstadoActionPerformed(evt);
            }
        });

        jLabel5.setText("CADASTRO DE MUNICIPIO NACIONAL");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(NovoJB)
                        .addGap(38, 38, 38)
                        .addComponent(InserirJB)
                        .addGap(44, 44, 44)
                        .addComponent(ExcluirJB)
                        .addGap(44, 44, 44)
                        .addComponent(SairJB))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 566, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rbClimaEquatorial)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rbClimaTropical)
                                        .addGap(18, 18, 18)
                                        .addComponent(rbClimaSubtropical)
                                        .addGap(18, 18, 18)
                                        .addComponent(rbClimaSemiarido))
                                    .addComponent(txtGastos, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txtPupolacao, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel5)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel1))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNomeMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSiglaEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(599, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNomeMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtSiglaEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPupolacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbClimaEquatorial)
                    .addComponent(rbClimaTropical)
                    .addComponent(rbClimaSubtropical)
                    .addComponent(rbClimaSemiarido)
                    .addComponent(jLabel3))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtGastos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(65, 65, 65)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SairJB)
                    .addComponent(ExcluirJB)
                    .addComponent(InserirJB)
                    .addComponent(NovoJB))
                .addGap(479, 479, 479))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeMunicipioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeMunicipioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeMunicipioActionPerformed

    private void NovoJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NovoJBActionPerformed
        limpar();
    }//GEN-LAST:event_NovoJBActionPerformed

    private void InserirJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InserirJBActionPerformed
        try {
            municipio = new Municipio();
            municipio.setNome(txtNomeMunicipio.getText());
            municipio.setFk_id_estado(txtSiglaEstado.getText());
            if (rbClimaEquatorial.isSelected()) {
                municipio.setClima("Equatorial");
            } else if (rbClimaTropical.isSelected()) {
                municipio.setClima("Tropical");
            } else if (rbClimaSubtropical.isSelected()) {
                municipio.setClima("Subtropical");
            } else if (rbClimaSemiarido.isSelected()) {
                municipio.setClima("Semiárido");
            }
            float gasto = Float.parseFloat(txtGastos.getText());
            municipio.setGastos(gasto);
            municipioDAO = new MunicipioDAO();
            municipioDAO.cadastrarMunicipio(municipio);           
            limpar();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao cadastrar o municipio!");
            System.err.println(e);
        }
    }//GEN-LAST:event_InserirJBActionPerformed

    private void ExcluirJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExcluirJBActionPerformed
        try {
            String nome = txtNomeMunicipio.getText();
            municipioDAO = new MunicipioDAO();
            municipioDAO.excluirMunicipio(nome);
            JOptionPane.showMessageDialog(null, "Municipio Excluido Com Sucesso!!!");
            limpar();
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Erro ao Excluir o municipio");
        }

    }//GEN-LAST:event_ExcluirJBActionPerformed

    private void tabelaMunicipiosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMunicipiosMouseClicked
        txtNomeMunicipio.setText(tabelaMunicipios.getValueAt(tabelaMunicipios.getSelectedRow(), 0).toString());
        txtSiglaEstado.setText(tabelaMunicipios.getValueAt(tabelaMunicipios.getSelectedRow(), 1).toString());
        txtPupolacao.setText(tabelaMunicipios.getValueAt(tabelaMunicipios.getSelectedRow(), 2).toString());
        String clima = tabelaMunicipios.getValueAt(tabelaMunicipios.getSelectedRow(), 3).toString();
        if (clima.equals("Equatorial")) {
            rbClimaEquatorial.setSelected(true);
        } else if (clima.equals("Tropical")) {
            rbClimaTropical.setSelected(true);
        } else if (clima.equals("Subtropical")) {
            rbClimaSubtropical.setSelected(true);
        } else if (clima.equals("Semiárido")) {
            rbClimaSemiarido.setSelected(true);
        }
        txtGastos.setText(tabelaMunicipios.getValueAt(tabelaMunicipios.getSelectedRow(), 4).toString());
        txtNomeMunicipio.setEditable(false);
        txtPupolacao.setEnabled(false);
        txtSiglaEstado.setEnabled(false);
        rbClimaEquatorial.setEnabled(false);
        rbClimaTropical.setEnabled(false);
        rbClimaSubtropical.setEnabled(false);
        rbClimaSemiarido.setEnabled(false);
               
        
    }//GEN-LAST:event_tabelaMunicipiosMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        Listar();
    }//GEN-LAST:event_formWindowActivated

    private void SairJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SairJBActionPerformed
        this.dispose();
    }//GEN-LAST:event_SairJBActionPerformed

    private void rbClimaEquatorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbClimaEquatorialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbClimaEquatorialActionPerformed

    private void txtSiglaEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSiglaEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSiglaEstadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Municipio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Municipio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Municipio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Municipio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MunicipioInterface dialog = new MunicipioInterface(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    private void limpar() {
        txtNomeMunicipio.setEnabled(true);
        txtSiglaEstado.setEnabled(true);
        rbClimaEquatorial.setEnabled(true);
        rbClimaSubtropical.setEnabled(true);
        rbClimaTropical.setEnabled(true);
        rbClimaSemiarido.setEnabled(true);
        txtGastos.setEnabled(true);        
        txtNomeMunicipio.setText("");
        txtSiglaEstado.setText("");
        txtGastos.setText("");
        txtNomeMunicipio.requestFocus();
    }

    public void Listar() {
        try {
            municipioDAO = new MunicipioDAO();
            List<Municipio> listarMunicipios = municipioDAO.listarMunicipios();
            DefaultTableModel modelo = (DefaultTableModel) tabelaMunicipios.getModel();
            modelo.setNumRows(0);
            for (Municipio mu : listarMunicipios) {
                modelo.addRow(new Object[]{
                    mu.getNome(),
                    mu.getFk_id_estado(),
                    mu.getPopulacao(),
                    mu.getClima(),
                    mu.getGastos(),});
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Erro ao Listar os municipios");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ExcluirJB;
    private javax.swing.JButton InserirJB;
    private javax.swing.JButton NovoJB;
    private javax.swing.JButton SairJB;
    private javax.swing.ButtonGroup bgClima;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JRadioButton rbClimaEquatorial;
    private javax.swing.JRadioButton rbClimaSemiarido;
    private javax.swing.JRadioButton rbClimaSubtropical;
    private javax.swing.JRadioButton rbClimaTropical;
    private javax.swing.JTable tabelaMunicipios;
    private javax.swing.JFormattedTextField txtGastos;
    private javax.swing.JFormattedTextField txtNomeMunicipio;
    private javax.swing.JFormattedTextField txtPupolacao;
    private javax.swing.JTextField txtSiglaEstado;
    // End of variables declaration//GEN-END:variables
}
