/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import java.awt.Color;

/**
 *
 * @author chris
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        this.setExtendedState(MAXIMIZED_BOTH);
        this.getContentPane().setBackground(Color.GRAY);        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        mncadastro = new javax.swing.JMenu();
        mnCadastroEstado = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnCadastroCidade = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mnsair = new javax.swing.JMenuItem();
        mnpesquisa = new javax.swing.JMenu();
        mnPesquisaClima = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        mnPesquisaDevedores = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        mnBuscaSigla = new javax.swing.JMenuItem();
        mnAdicionarGasto = new javax.swing.JMenu();
        mnAdicionarGastoMunicipio = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Orçamento Nacional");

        mncadastro.setMnemonic('c');
        mncadastro.setText("Cadastro");

        mnCadastroEstado.setMnemonic('a');
        mnCadastroEstado.setText("Estado");
        mnCadastroEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnCadastroEstadoActionPerformed(evt);
            }
        });
        mncadastro.add(mnCadastroEstado);
        mncadastro.add(jSeparator1);

        mnCadastroCidade.setText("Municipio");
        mnCadastroCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnCadastroCidadeActionPerformed(evt);
            }
        });
        mncadastro.add(mnCadastroCidade);
        mncadastro.add(jSeparator2);

        mnsair.setMnemonic('s');
        mnsair.setText("Sair");
        mnsair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnsairActionPerformed(evt);
            }
        });
        mncadastro.add(mnsair);

        jMenuBar1.add(mncadastro);
        mncadastro.getAccessibleContext().setAccessibleName("adastro");

        mnpesquisa.setText("Pesquisa");

        mnPesquisaClima.setText("Busca/Clima");
        mnPesquisaClima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnPesquisaClimaActionPerformed(evt);
            }
        });
        mnpesquisa.add(mnPesquisaClima);
        mnpesquisa.add(jSeparator3);

        mnPesquisaDevedores.setText("Busca/Devedores");
        mnPesquisaDevedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnPesquisaDevedoresActionPerformed(evt);
            }
        });
        mnpesquisa.add(mnPesquisaDevedores);
        mnpesquisa.add(jSeparator4);

        mnBuscaSigla.setText("Busca/Silga");
        mnBuscaSigla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnBuscaSiglaActionPerformed(evt);
            }
        });
        mnpesquisa.add(mnBuscaSigla);

        jMenuBar1.add(mnpesquisa);

        mnAdicionarGasto.setText("Adicionar");

        mnAdicionarGastoMunicipio.setText("Gastos do Municipio");
        mnAdicionarGastoMunicipio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnAdicionarGastoMunicipioActionPerformed(evt);
            }
        });
        mnAdicionarGasto.add(mnAdicionarGastoMunicipio);

        jMenuBar1.add(mnAdicionarGasto);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 618, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 413, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnCadastroEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnCadastroEstadoActionPerformed
            new EstadoInterface(null,true).setVisible(true);
            
        
// TODO add your handling code here:
    }//GEN-LAST:event_mnCadastroEstadoActionPerformed

    private void mnCadastroCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnCadastroCidadeActionPerformed
        new MunicipioInterface(null,true).setVisible(true);
    }//GEN-LAST:event_mnCadastroCidadeActionPerformed

    private void mnsairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnsairActionPerformed
        this.dispose();
    }//GEN-LAST:event_mnsairActionPerformed

    private void mnPesquisaClimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnPesquisaClimaActionPerformed
        new BuscaClima(null,true).setVisible(true);
    }//GEN-LAST:event_mnPesquisaClimaActionPerformed

    private void mnPesquisaDevedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnPesquisaDevedoresActionPerformed
        new Devedores(null,true).setVisible(true);
    }//GEN-LAST:event_mnPesquisaDevedoresActionPerformed

    private void mnAdicionarGastoMunicipioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnAdicionarGastoMunicipioActionPerformed
        new AdicionarGastos(null,true).setVisible(true);
    }//GEN-LAST:event_mnAdicionarGastoMunicipioActionPerformed

    private void mnBuscaSiglaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnBuscaSiglaActionPerformed
        new BuscaDeMunicipiosDoEstado(null,true).setVisible(true);
    }//GEN-LAST:event_mnBuscaSiglaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
          
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JMenu mnAdicionarGasto;
    private javax.swing.JMenuItem mnAdicionarGastoMunicipio;
    private javax.swing.JMenuItem mnBuscaSigla;
    private javax.swing.JMenuItem mnCadastroCidade;
    private javax.swing.JMenuItem mnCadastroEstado;
    private javax.swing.JMenuItem mnPesquisaClima;
    private javax.swing.JMenuItem mnPesquisaDevedores;
    private javax.swing.JMenu mncadastro;
    private javax.swing.JMenu mnpesquisa;
    private javax.swing.JMenuItem mnsair;
    // End of variables declaration//GEN-END:variables
}
